netzstrategen/wordpress-shop-standards

- src/WooCommerce.php
- [Mails: all product attributes are shown](https://app.asana.com/0/inbox/383242129844222/1115195838885601/1115208929366270)
> Fixed duplicated attributes were displayed in order details table.

- package.json
- plugin.php
- src/WooCommerce.php
- [Remove custom price labels from related products](https://app.asana.com/0/383242129844224/1117001017270597)
> Fixed price custom label was displayed for related and cross-sell products.

- package.json
- plugin.php
- src/WooCommerce.php
- [Re-arrange attributes in cart/checkout/mails](https://app.asana.com/0/inbox/383242129844222/1115324507386397/1117050697493693)
> Fixed order of products details in cart, checkout and order email.

- package.json
- plugin.php
- src/WooCommerce.php
- [Re-arrange attributes in cart/checkout/mails](https://app.asana.com/0/inbox/383242129844222/1115324507386397/1120890224846063)
> Fixed delivery time and MOEVE IDs were not displayed at top position in cart, checkout and order email.

- src/Plugin.php
- src/widgets/WidgetLayeredNav.php
- src/widgets/WidgetLayeredNavFilters.php
- See base branch
- Refactored code to not rely on widget class overrides but use DOM traversal to achieve the desired changes instead
> Refactored code.

- src/WooCommerce.php
- src/widgets/WidgetFilterDeliveryTime.php
- src/widgets/WidgetLayeredNavFilters.php
> Added numeric sorting for delivery time slugs.

- src/ProductFilters/WidgetFilterDeliveryTime.php
> Fixed taxonomy query var might be NULL.

- package.json
- plugin.php
- src/ProductFilters/WidgetFilterDeliveryTime.php
- 🙈 sorry… committed untested code. This PR fixes the issue.
> Fixed taxonomy might be type NULL.

- package.json
- plugin.php
- src/WooCommerce.php
- [Related Ticket](https://app.asana.com/0/30156186242982/1123159956543924/f)
> Fixed order of item attributes in confirmation mail.

- package.json
- plugin.php
- src/WooCommerce.php
- [Related Ticket](https://app.asana.com/0/784106262441860/1136103500287444/f) (internal only)
- When checking "Display sale price as normal price" it removes other components which were added via the `woocommerce_get_price_html` filter as the price is getting overridden
> Fixed sale price as regular price removes energy label.

- package.json
- plugin.php
- [Fatal error in plugin shop-standards](https://app.asana.com/0/809933051638353/1134306736653764/f)
> Updated plugin version to 1.24.4.

- src/WooCommerce.php
- [Sale bubble has double minus sign before price](https://app.asana.com/0/784106262441860/1138226527906153/f)
> Fixed woocommerce sale bubble showing double minus percentage.

- src/Plugin.php
- src/Schema.php
- [Missing GTIN in schema.org on single product pages](https://app.asana.com/0/784106262441860/1141746824096192/f)
> Fixed missing gtin product number for single product pages.

- src/Plugin.php
- src/Schema.php
- src/Seo.php
- [Missing brand in schema.org on single product pages](https://app.asana.com/0/106767930274882/1141746824096235)
> Added product brand to schema.org structured data.

- package.json
- plugin.php
- src/WooCommerce.php
> Fixed PHP error and minor code cleanup.

- package.json
- plugin.php
- src/Performance.php
- src/Plugin.php
- [Defer or dequeue WooCommerce assets on non-WooCommerce pages](https://app.asana.com/0/383242129844224/1141315041731476)
-
> Fixed scripts synchronous loading was decreasing site pages performance.

- package.json
- plugin.php
- src/Admin.php
- src/Plugin.php
- [Automate sale label (category) assignment](https://app.asana.com/0/inbox/106767930205241/1138362657798199/1156166804867037)
> Fixed sale category does not get assigned on product update.

- package.json
- plugin.php
- src/Admin.php
- Error reported on Slack by @stephansperling . https://netzstrategen.slack.com/archives/C8RP4J0MR/p1578917736000500
> Fixed PHP error thrown in backend when product delivery time is not set.

- src/WooCommerce.php
- Reported on Slack: https://netzstrategen.slack.com/archives/CLGJ41RPW/p1583139064004300?thread_ts=1583137850.003700&cid=CLGJ41RPW
> Fixed backorder allowed is forced for all products.

- package.json
- plugin.php
- src/Admin.php
- Sale percentage was wrongly calculated/updated for variable products. Reported by @Henning-Richters on Slack: https://netzstrategen.slack.com/archives/CCGG11CSF/p1584717719009100
> Fixed sale percentage was not correctly updated for variable products.

- package.json
- plugin.php
- src/Admin.php
- [Sale Bubble not updated when_sale_price_dates_from is set](https://app.asana.com/0/809933051638353/1166600580702113/f)
-
> Fixed sale percentage was not recalculated after product price update.

- package.json
- plugin.php
- src/ProductFilters/WidgetFilterDeliveryTime.php
- src/Seo.php
- [No filters are displayed after using the price slider](https://app.asana.com/0/784106262441860/1170209490459561/f)
-
> Fixed products filter sidebar was empty after applying filters.

- package.json
- plugin.php
- src/Plugin.php
- src/Seo.php
- [Wrong non-euro prices in schema.org](https://app.asana.com/0/809933051638353/1175777161118852)
> Fixed wrong non-euro schema.org prices on single product template.

- package.json
- plugin.php
- src/Plugin.php
- src/Seo.php
- src/WooCommerce.php
- [Different prices for product variants in schema.org and google shopping feed](https://app.asana.com/0/1156709897787098/1170010894141553)
-
> Fixed product variation price was not added to schema.org.

- package.json
- plugin.php
- src/Seo.php
- [Different prices for product variants in schema.org and google shopping feed](https://app.asana.com/0/1156709897787098/1170010894141553)
- Issue reported by @Henning-Richters [on Slack](https://netzstrategen.slack.com/archives/CCGG11CSF/p1592390063003200).
> Fixed schema.org data for simple products was incomplete.

- package.json
- plugin.php
- src/Plugin.php
- src/Seo.php
- [Mismatched delivery time between front end an schema.org WOPA](https://app.asana.com/0/587433704548192/1181137040910250/f)
-
> Fixed product availability entry in schema.org.

- package.json
- plugin.php
- src/WooCommerce.php
- [Fix after-update issue: Remove horizontal line on online order success summary](https://app.asana.com/0/809933051638353/1188432965639572/f)
> Fixed erroneous horizontal rule on order confirmation page.

- package.json
- plugin.php
- src/WooCommerce.php
- [Fix PHP notice in some product pages](https://app.asana.com/0/106767930274882/1187839482906991)
> Fixed PHP Fatal Error if variable product have no defined variations.

- package.json
- plugin.php
- src/WooCommerceCheckout.php
- [Fix after-update issue: wrong placement of email field on page /kasse](https://app.asana.com/0/106767930274882/1187994526874393)
> Fixed confirmation email field wrong position.

- plugin.php
- src/WooCommerce.php
- [Some html code is shown in the card page on the frontend](https://app.asana.com/0/106767930274882/1188270288603619)
> Fixed HTML tags were shown on coupon field on mobile cart page.

- package.json
- plugin.php
- src/WooCommerce.php
- [_shop-standards_show_sale_price_only broken on product detail pages & related products](https://app.asana.com/0/30156186242982/1190933470177681/f)
-
> Fixed striked normal price was displayed for variable products regardless of backend setting.

- package.json
- plugin.php
> Bumped version to 1.36.3.

- package.json
- plugin.php
- src/WooCommerce.php
- [Coupons: description not visible in frontend (cart)](https://app.asana.com/0/809933051638353/1190760513368905)
> Fixed coupon label is missing description and extra space.

- package.json
- plugin.php
- src/Performance.php
- src/Plugin.php
- src/WooCommerce.php
- [Poor values for LCP on mobile devices | WOPA & LART](https://app.asana.com/0/809933051638353/1189713486865785/f)
> Added preload for main WooCommerce product image.

- package.json
- plugin.php
- src/WooCommerceCheckout.php
- https://app.asana.com/0/1192898135376417/1190726974872409/f
-
> Added removal for shipping city field calculation.

- package.json
- plugin.php
- src/WooCommerce.php
- [Exclude standard shipping time (listed in product details) from order confirmation](https://app.asana.com/0/1156709897787098/1199584623296285)
-
> Fixed product attributes could not be excluded from purchase confirmation email.

- src/WooCommerce.php
- [Valid four-digit Liechtenstein postcodes marked as invalid, stopping orders](https://app.asana.com/0/587433704548192/1199387326781845/f)
> Fixed length postcode validation for Liechtenstein.

- package.json
- plugin.php
- src/Admin.php
- src/Plugin.php
- src/WooCommerce.php
- [Hide "related products" section in frontend for certain products.](https://app.asana.com/0/30156186242982/1199229224946101/f)
-
>  Added feature to disable related products on a per-product basis.

- package.json
- plugin.php
- [Prevent pagination links to page 1 that contain the page suffix. ](https://app.asana.com/0/507013885678070/1200321868255267/f)
- Need to bump plugin version to update using composer.
> Bumped plugin version from 1.38.2 to 1.38.3.

- package.json
- plugin.php
- src/Plugin.php
- [Prevent pagination links to page 1 that contain the page suffix. ](https://app.asana.com/0/507013885678070/1200321868255267/f)
-
> Fixed trailing slash issue with pagination and query parameters.

- src/Plugin.php
> Fixed pagination links for page 10 are wrongly manipulated.

- package.json
- plugin.php
- src/Plugin.php
- src/ProductAttributePageTitle.php
- src/WooCommerce.php
- [Product Attribute Listings: Optional field for custom page title instead of attribute/term/filter name](https://app.asana.com/0/809933051638353/1200232830814947/f)
-
> Added optional title for product attribute listing pages.

- src/Seo.php
- [Google crawls a lot of URLs with the parameter amazon_payments_advanced](https://app.asana.com/0/809933051638353/1200047523031022/f)
-
> Fixed Google bot indexes URLs in the JavaScript of the woocommerce-gateway-amazon-payments-advanced plugin.

- src/Plugin.php
- src/ProductAttributePageTitle.php
> Fixed fatal errors if advanced-custom-fields plugin is not installed.

- src/ProductFilters/DeliveryTime.php
- [Express Filter: remove products with back in stock date](https://app.asana.com/0/30156186242982/1200414049060460/f)
-
> Removed products with future back in stock dates from delivery time filter results.

- package.json
- plugin.php
- src/ProductFilters/DeliveryTime.php
- [Express Filter: remove products with back in stock date](https://app.asana.com/0/30156186242982/1200414049060460/f)
-
> Fixed delivery time filter was not filtering out backorder products.

- package.json
- plugin.php
- src/Admin.php
- src/Plugin.php
- src/ProductAttributePageTitle.php
Fixups for https://github.com/netzstrategen/wordpress-shop-standards/pull/145
> Improved performance of optional title for product attribute listing pages.

- package.json
- plugin.php
- src/ProductFilters/DeliveryTime.php
- reverted delivery time filter conditions to the previous correct ones, this was trying to fix most probably a Elasticsearch issue
> Fixed delivery time filter excludes products allowing backorders.

- package.json
- plugin.php
- src/WooCommerceCheckout.php
https://app.asana.com/0/1201154968324561/1201075091917011/f
> Removed email & billing address checkout validation in AmazonV2Pay.

- package-lock.json
- package.json
- src/ProductsPermalinks.php
https://app.asana.com/0/1200981693019240/1201538907448298
We missed a detail on the previous fix which is now affecting draft previews, so now it will only work for published products as intented.
> Fixed condition to change only published product links allowing draft previews.

- src/Amazon.php
- src/Plugin.php
- src/WooCommerce.php
Ticket
https://app.asana.com/0/1201154968324561/1201524725231586/f
> Added filter to replace order ID of imported Amazon orders with custom order ID.

- src/Seo.php
Reverts netzstrategen/wordpress-shop-standards#154
See latest comments on [Google crawls a lot of URLs with the parameter amazon_payments_advanced](https://app.asana.com/0/809933051638353/1200047523031022/f)
> Revert "Fixed Google bot indexes URLs in the JavaScript of the woocommerce-gateway-amazon-payments-advanced plugin."

- src/ProductAttributePageTitle.php
- [Provide a field for specifying a special H1 heading on category pages. | GACO](https://app.asana.com/0/30156186242982/1201045413230014/f)
-
> Added custom page title field to product categories.

- src/Amazon.php
- src/Plugin.php
https://app.asana.com/0/30156186242982/1192093200609628/f
> Added filter hook to add shipping method to imported Amazon orders.

- src/Amazon.php
https://app.asana.com/0/30156186242982/1192093200609628/f
Related to: https://github.com/netzstrategen/gaco/pull/762
> Added null check on order param.

- src/Plugin.php
- src/ProductFieldsManager.php
- src/WooCommerce.php
https://app.asana.com/0/1200981693019240/1201650447034014
> Added condition to display custom product fields.

- src/Amazon.php
https://app.asana.com/0/0/1201518907016467/f
> Fixed PHP notice/warning if  no available methods.

- package.json
- plugin.php
- src/WooCommerceCheckout.php
https://app.asana.com/0/30156186242982/1201940215532388/f
> Fixed street is missing in billing address for German orders paid with Amazon Pay.

- src/Plugin.php
- src/ProductFeeds.php
- [Product feeds: add full category path to certain feeds](https://app.asana.com/0/30156186242982/1201946855484892/f)
> Added product feeds full category path.

- src/Amazon.php
- src/Plugin.php
https://app.asana.com/0/30156186242982/1202079388310636/f
> Added missing shipping instance ID for Amazon order import.

- package.json
- plugin.php
- src/Plugin.php
- src/WooCommerce.php
- [Allow to add more than one product to cart via URL](https://app.asana.com/0/1199938965307042/1202031768897952/f)
> Allow to add multiple products to the cart.

- package.json
- plugin.php
- [Allow to add more than one product to cart via URL](https://app.asana.com/0/1199938965307042/1202031768897952/f)
> Bumped plugin version to 1.44.0.

- package.json
- plugin.php
- src/Plugin.php
- src/WooCommerce.php
- [Follow up on "Customer account: Change/delete delivery time in order confirmation"](https://app.asana.com/0/1199938965307042/1202049060330720/f)
> Fixed delivery time of items in past orders is not immutable.

- src/Plugin.php
> Fixed used hook as filter instead of action.

- src/WooCommerce.php
- [Optimize prices on listing pages & detail pages](https://app.asana.com/0/1202197213338206/1202380367079160)
> Added spaces and changed dash for product price range.

- package.json
- plugin.php
- src/Plugin.php
- src/WooCommerce.php
https://app.asana.com/0/0/1202584852391692/f
> Added delete orphans variants cron event.

- src/Plugin.php
- src/WooCommerce.php
- [Add custom meta fields to orders](https://app.asana.com/0/1201940451841784/1202635304001298)
> Added customer metafields for mailchimp use.

- src/Plugin.php
- src/WooCommerce.php
- src/WooCommerceShippingPackages.php
https://app.asana.com/0/30156186242982/1203020088063708/f
> Added split package info in email orders.

- src/Amazon.php
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1207548184000912
> fix: amazon order import error

- src/WooCommerce.php
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1208661830459021
> feat: rename product options fields

- src/Admin.php
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1208770722582157
> fix: warning undefined notice

- src/Plugin.php
- src/ProductFeeds.php
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1211020624309164
> feat: remove image with text in feed
