netzstrategen/wordpress-shop-standards

- package.json
- plugin.php
- src/WooCommerce.php
- [Mails: all product attributes are shown](https://app.asana.com/0/383242129844224/1115195838885601)
- PHP Fatal error
> Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method WC_Product_Simple::get_variation_attributes() in /var/www/vhosts/gartenmoebelcompany.de/htdocs/wp-content/p      lugins/shop-standards/src/WooCommerce.php:569
> Fixed PHP fatal error when retrieving simple product attributes.

- src/Plugin.php
- [Optimize product titles in order confirmation mail](https://app.asana.com/0/inbox/383242129844222/1123159956543922/1123733355026157)
See https://github.com/netzstrategen/wordpress-shop-standards/pull/31
> Fixed SKU was not removed by default from order items name in notification emails.

- plugin.php
- src/Admin.php
- src/Plugin.php
- When cron jobs are run, the registered plugin admin hooks are not invoked which prevents some desired behaviour if, for example, posts are updated.
- To prevent this, we call the admin init method manually when doing cron.
> Fixed admin hooks are not invoked for cron jobs.

- package.json
- plugin.php
- src/WooCommerce.php
- [Fatal error in plugin shop-standards](https://app.asana.com/0/809933051638353/1134306736653764/f)
- PHP fatal error were still happening.
> Fixed fatal error thrown when avanced-custom-fields plugin is not installed.

- package.json
- plugin.php
- src/Admin.php
- [Shortest delivery time on the overview page not correct](https://app.asana.com/0/383242129844224/1127550128825839)
- Parent product delivery time is not updated with the lowest value from its variations when saved using the edit product page "Update" button.
> Fixed product delivery time was not updated with the lowest value from its variations.

- package.json
- plugin.php
- src/Seo.php
- []()
- A PHP error is thrown when product brand taxonomy does not exist.
> Fatal error: Uncaught Error: Cannot use object of type WP_Error as array in /var/www/vhosts/stage.nutr.netz.rocks/htdocs/wp-content/plugins/shop-standards/src/Seo.php:121 Stack trace: #0 /var/www/vhosts/stage.nutr.netz.rocks/htdocs/wp-includes/class-wp-hook.php(288): Netzstrategen\ShopStandards\Seo::getProductBrand(Array) #1 /var/www/vhosts/stage.nutr.netz.rocks/htdocs/wp-includes/plugin.php(208): WP_Hook->apply_filters(Array, Array) #2 /var/www/vhosts/stage.nutr.netz.rocks/htdocs/wp-content/plugins/woocommerce/includes/class-wc-structured-data.php(321): apply_filters('woocommerce_str...', Array, Object(WC_Product_Simple)) #3 /var/www/vhosts/stage.nutr.netz.rocks/htdocs/wp-includes/class-wp-hook.php(286): …
> Fixed PHP error when product brand taxonomy does not exist.

- package.json
- plugin.php
- src/WooCommerce.php
- [Show low stock levels in frontend](https://app.asana.com/0/30156186242982/1133642108266488/f)
- Products can be ordered even if stock level is zero.
- Previously, "only 0 in stock" was shown in this scenario.
> Fixed incorrect notice when zero stock but backorder possible.

- package.json
- plugin.php
- src/Admin.php
- [Sale Bubble shows wrong value "-0 %" / NUTR & LOFI](1154739415381321)
-
> Fixed sale percentage was not updated for bundle products.

- package.json
- plugin.php
- src/Plugin.php
- src/WooCommerce.php
- src/WooCommerceSaleLabel.php
- [Refactor automated sale label by category assignment](https://app.asana.com/0/484879736575808/1156525162487127)
- The functionality has been moved into its own class called `WooCommerceSaleLabel`.
- Option names have been renamed to be more descriptive.
In order to update the database, the following code would need to be run (through `WP-CLI`?):
```
<?php 
$map_names = [
'_shop-standards_enable_auto_sale_category_assignment' => '_shop-standards_sale_auto_label_enabled',
'_shop-standards_eligible_delivery_times' => '_shop-standards_sale_auto_label_delivery_times',
'_shop-standards_sale_category' => '_shop-standards_sale_auto_label_category',
]
foreach ($map_names as $old => $new) {
$old_option_value = get_option($old);
if ($old_option_value) {
if (update_option($new, $old_option_value)) …
```
> Refactored auto sale category assignment into seperate class.

- package.json
- plugin.php
- src/Performance.php
- A PHP Notice is displayed when trying to defer the enqueueing of scripts:
> Notice: Undefined index: select2 in /Users/joan/Sites/netzstrategen/nutr/nutr/htdocs/wp-content/plugins/shop-standards/src/Performance.php on line 89
> Fixed PHP notice when trying to defer enqueuing of scripts.

- src/ProductFilters/WidgetFilterDeliveryTime.php
- A PHP notice was thrown in filter by delivery time widget if delivery time tem id is not defined.
```
Notice: Undefined index: delivery_time-9641 in /Users/joan/Sites/netzstrategen/gaco/htdocs/wp-content/plugins/shop-standards/src/ProductFilters/WidgetFilterDeliveryTime.php on line 80
```
> Fixed PHP notice in delivery time filter widget.

- package.json
- plugin.php
- src/Admin.php
- Reported by @sun on Slack: https://netzstrategen.slack.com/archives/CAMP1MQJ2/p1586187404017700
- Caused by previous refactoring: https://github.com/netzstrategen/wordpress-shop-standards/commit/71654ed0a9da1c1f0198e13e6a7f1ce18acb0397
> Fixed PHP notice caused by missing method in class WooCommerce.

- package.json
- plugin.php
- src/PlusProducts.php
- [Fix Plus Product warning message is displayed on empty carts](https://app.asana.com/0/106767930274882/1175093376311869)
> Fixed Plus Products error message was shown if the cart was empty.

- package.json
- plugin.php
- src/Plugin.php
- src/Seo.php
- [Non-euro prices in the source code do not match the displayed prices](https://app.asana.com/0/809933051638353/1175777161118852/f)
-
> Fixed wrong non-euro schema.org prices on single product template.

- package.json
- plugin.php
- src/Plugin.php
- src/WooCommerce.php
- I couldn't find the history for the deprecation but given this answer, https://stackoverflow.com/a/46009513/2862127, `woocommerce_variable_sale_price_html` is deprecated since WC 3.0.
- I used another `woocommerce_get_price_html` hook as it seems some plugins are using this hook to override the output from the variable once again. Please see https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-product-variable.php#L167-L170
> Fixed strike price for variable products might not be displayed.

- src/Performance.php
- [Assets on GACO are loaded twice](https://app.asana.com/0/809933051638353/1192191068119417)
> Fixed loading header scripts twice due to preloading with wrong  query argument.

- src/Admin.php
- [Remove WordPress release update and WooCommerce.com bragging notices](https://app.asana.com/0/354170587449545/1197780930151545/f)
-
> Fixed WordPress admin UI is cluttered with messages notifying about new releases and more features.

- package.json
- plugin.php
- src/WooCommerce.php
- [Valid four-digit Liechtenstein postcodes marked as invalid, stopping orders](https://app.asana.com/0/587433704548192/1199387326781845/f)
> Fixed postcode validation was always false for LI and NL.

- package.json
- plugin.php
- src/Plugin.php
- [ES: instant search results show sale bubbles even when deactivated](https://app.asana.com/0/587433704548192/1191855237961641/f)
Percentage sale bubbles markup is indexed into ES, but `sale_percentage_output` was registered too late and not available for the ES index update.
> Fixed instant search results show desynced sale bubbles.

- package.json
- plugin.php
- src/WooCommerce.php
- ["Back in stock"-date/delivery time: optimization](https://app.asana.com/0/587433704548192/1199601303851103/f)
> Fixed back in stock date on product detail page not prominent enough.

- assets/styles/main.scss
- dist/styles/main.min.css
- package.json
- plugin.php
- src/Plugin.php
- ["hide add to cart button" checkbox not working for variable products](https://app.asana.com/0/30156186242982/1200029023488134/f)
- Custom "Hide add to cart button" (added [here](https://github.com/netzstrategen/wordpress-shop-standards/commit/690d6c870911f709be1ffb65456d0fc2ed21cfad)) works for single products but not variations
- Button+quantity section is changed via JS so not feasible to remove completely via PHP
- 'disabled' class added to button is used in JS to prevent purchases so CSS-only hide here is ok
> Fixed variations add to cart button not hidden when custom option set.

- package.json
- plugin.php
- src/Seo.php
- A product should be shown as available if any of a variant is in stock regardless of the parent product.
> Fixed incorrect product availability schema.

- src/Plugin.php
- src/WooCommerce.php
- [Prevent pagination links to page 1 that contain the page suffix. ](https://app.asana.com/0/507013885678070/1200321868255267/f)
-
> Fixed first page link in pagination causes redirect to actual initial listing page.

- src/WooCommerce.php
- [Variable Products: missing "back in stock"-date (overview pages)](https://app.asana.com/0/809933051638353/1200306165872411)
The "back in stock" date was visible for "simple products" only. The reason is that the logic was only getting the date from the "master product", which only works for "simple products" since such date is stored on each product variation. This PR extends the current logic by gathering the "EarliestBackInStock" date either from the master product (in the case of simple products) or from variations (in the case of variable products).
> Fixed back-in-stock not showing for variable products in products listing.

- src/WooCommerce.php
- [Customer account: Change/delete delivery time in order confirmation](https://app.asana.com/0/30156186242982/1200426661151439/f)
-Changes have been made to staging to show the delivery time in the order confirmation as it was specified at the moment of the order. This instead of using the current product delivery time property
> Fixed delivery time in order confirmation use value at order time

- package.json
- plugin.php
- src/Plugin.php
- src/Schema.php
- src/WooCommerce.php
- [shop-standards: Obsolete back in stock dates are not removed from database](https://app.asana.com/0/30156186242982/1200496606141091/f)
> Added cronjob to remove outdated back-in-stock metadata for products without Moeve ID.

- src/WooCommerce.php
https://app.asana.com/0/784106262441860/1201312032738062/f
The problem was the amount of times the function woocommerce_de_get_deliverytime_string_label_string was been called in the listing pages, triggering even more subqueries from it, at least ny removing the Product Variation objects from the calling stack I was able to reduce the local page loading by more than half... 
I refactored also the function to format the back in stock date which was doing an extra condition to make sure the date was a valid future date when the it has been done in the previous step in all cases.
> Fixed performance bottleneck caused by earliest back in stock functionality.

- src/WooCommerce.php
- [PHP warning  on shop-standards page](https://app.asana.com/0/809933051638353/1200676005221602/f)
- The code does not use the API correctly and attempts to operate on an empty/error result.
> Fixed PHP warning on settings page if there are no product categories yet.

- src/Plugin.php
- src/ProductFilters/DeliveryTime.php
- src/ProductFilters/WidgetLayeredNavFilters.php
https://app.asana.com/0/1200981693019240/1201452351682360
For some reason the same code shared between Gaco and Wopa, the widgets were being registered in a different order on this last one, which was causing a malfunction, so increasing the hook priority seem to be fine again, I took the chance to remove some clear redundancy in the code in order to improve any future maintenance.
> Fixed express delivery filter cannot be disabled.

- src/Plugin.php
- src/WooCommerce.php
- https://app.asana.com/0/0/1201713901084428/f
- Original task that introduced the recursive call: https://app.asana.com/0/784106262441860/1136103500287444/f
> Fixed duplicate sale labels after updating woocommerce-german-market.

- src/WooCommerce.php
- src/WooCommerceCheckout.php
Discovered during debugging of GACO updates.
Problem
- When disabling woocommerce to debug a certain behavior, then shop-standards causes a fatal error.
Unclear
- Not sure whether this is the best way. Maybe it is better to not register the hooks in init in the first place instead of checking in the individual callbacks.
> Fixed fatal error if woocommerce is not enabled.

- src/ProductsPermalinks.php
- [Fatal error when creating Woo Feeds](https://app.asana.com/0/784106262441860/1201457208483018/f)
> Fixed PHP fatal error caused by 'wpseo_canonical' filter.

- src/Plugin.php
- src/Seo.php
[Specification of brand not added in schema markup on product pages](https://app.asana.com/0/30156186242982/1199997679462445)
> Removed custom product brand schema output in favor of woocommerce-brands plugin.

- src/Plugin.php
- src/Seo.php
- [Product: Structured brand schema.org data missing on product detail pages](https://app.asana.com/0/587433704548192/1202348023753929)
- 4678e6e647909a1815d22f109645db2ed97e217c removed the custom output in favor of the plugin woocommerce-brands, but WOPA/LAMP does not use the plugin.
- This PR restores the original output (and fixes the structured data), but only outputs it if the woocommerce-brands plugin is not installed.
> Fixed structured markup for brand missing on product detail pages.

- src/ProductsPermalinks.php
- [Various PHP Fatal errors, errors, warnings](https://app.asana.com/0/809933051638353/1202430764055301)
- https://github.com/netzstrategen/wordpress-shop-standards/pull/190 attempted to fix a fatal error due to an empty argument being passed, but did not take into account that the return type hint still declares a `string` to be returned (the argument passed from `wpseo_canonical` is `null`): https://github.com/netzstrategen/wordpress-shop-standards/blob/6a3a09c801df229b23b34f93f51762f49aad136d/src/ProductsPermalinks.php#L33-L38
> Fixed PHP Fatal error: Uncaught TypeError: Return value must be of type string, null returned.

- src/Plugin.php
- src/WooCommerce.php
- src/WooCommerceCheckout.php
Fixes a fatal error introduced by https://github.com/netzstrategen/wordpress-shop-standards/pull/214 (for [Add custom meta fields to orders](https://app.asana.com/0/1201940451841784/1202635304001298)) ([Slack thread](https://netzstrategen.slack.com/archives/CLGJ41RPW/p1662557855312009?thread_ts=1662553421.058559&cid=CLGJ41RPW))
- Lots of fatal errors are happening since last deployment on Monday and hundreds of orders were not be able to be placed.
- The new code to track counts of orders per customer assumes that every customer would always create a user account.  But anonymous checkouts are possible.
- This causes the code to load all orders that are associated with user ID 0 (a lot).
- In turn, the server runs out of memory, halting in a fatal error.
> Fixed fatal error during checkout if customer does not create account.

- src/WooCommerceCheckout.php
- [Follow up on "Add custom meta fields to orders"](https://app.asana.com/0/1202867909936929/1202971033917628)
- Removed the code for _shop-standards_customer_orders_count
- The condition in the if was changed and not removed in order to make the wc_get_orders call only when the metafield is initially created.
> Removed unnecessary orders count metafield.
